name: smart_retail_bookstore
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  go_router: ^6.0.0
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
      - assets/.env.local
      - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.otf