name: smart_retail_bookstore
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/saikiransomanagoudar/smart-retail-bookstore-flutter-dart

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.0.0
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.1.14
  carousel_slider: ^4.2.1
  flip_card: ^0.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons-Regular.otf